using lab2.Models;
using System.Collections.Generic;
using System.Runtime.Serialization.Json;
using System.IO;

namespace lab2.DataContainers {
    public static class DataContainer {
        private static readonly DataContractJsonSerializer jsonFormatterForSubjects;
        private static readonly DataContractJsonSerializer jsonFormatterForLecturers;

        public static LecturerModel LecturerModel { get; set; }
        public static List<LecturerModel> Lecturers { get; set; }
        public static List<SubjectModel> Subjects { get; set; }

        private static string pathToSubjects = @"subjects.json";
        private static string pathToLecturers = @"lecturers.json";

        static DataContainer() {
            jsonFormatterForSubjects = new DataContractJsonSerializer(typeof(List<SubjectModel>));
            jsonFormatterForLecturers = new DataContractJsonSerializer(typeof(List<LecturerModel>));
            LecturerModel = null;
            GetLecturersFromJsonFile();
            GetSubjectsFromJsonFile();
        }

        private static void SetCustomLocation(string FileName) {
            if (FileName.Equals(string.Empty)) {
                return;
            }
            pathToSubjects = FileName + ".json";
            pathToLecturers = "autogenerated_" + FileName + ".json";
        }

        public static void Open(string FileName) {
            SetCustomLocation(FileName);
            GetLecturersFromJsonFile();
            GetSubjectsFromJsonFile();
        }

        public static void SaveAs(string FileName) {
            SetCustomLocation(FileName);
            SerializeSubjects();
            SerializeLecturers();
        }

        private static void ClearFileContent(string path) {
            if (File.Exists(path)) {
                File.WriteAllText(path, string.Empty);
            }
        }

        private static void GetLecturersFromJsonFile() {
            Lecturers = new List<LecturerModel>();
            if (File.Exists(pathToLecturers)) {
                using(FileStream fs = new FileStream(pathToLecturers, FileMode.Open)) {
                    Lecturers = (List<LecturerModel>)jsonFormatterForLecturers.ReadObject(fs);
                }
            }
        }

        private static void GetSubjectsFromJsonFile() {
            Subjects = new List<SubjectModel>();
            if (File.Exists(pathToSubjects)) {
                using (FileStream fs = new FileStream(pathToSubjects, FileMode.Open)) {
                   Subjects = (List<SubjectModel>)jsonFormatterForSubjects.ReadObject(fs);
                }
            }
        }

        public static void SerializeLecturers() {
            ClearFileContent(pathToLecturers);
            using (FileStream fs = new FileStream(pathToLecturers, FileMode.OpenOrCreate)) {
                jsonFormatterForLecturers.WriteObject(fs, Lecturers);
            }
        }

        public static void SerializeSubjects() {
            ClearFileContent(pathToSubjects);
            using (FileStream fs = new FileStream(pathToSubjects, FileMode.OpenOrCreate)) {
                jsonFormatterForSubjects.WriteObject(fs, Subjects);
            }
        }
    }
}